Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: org.om.CURA
      CodeUri: D:\git\Group_Compliance\CURA
      Runtime: java8
      Architectures:
        - x86_64